### ISSUE TITLE
Add tests for Hydrodynamics plugin

### ISSUE THREAD

**Issue by chapulina** [gazebosim/gz-sim#1273]
The plugin was added in #749 without tests. Since then, we've forked the plugin upstream in https://github.com/osrf/lrauv/blob/main/lrauv_ignition_plugins/src/HydrodynamicsPlugin.hh and made tweaks to fix bugs in the code. We should eventually port those fixes here and add tests verifying that the plugin behaves as expected.

## Desired behavior

A new integration test that tests various aspects of the hydrodynamics plugin.

## Implementation suggestion

The test should verify the hydrodynamics in isolation, so we're sure we're testing the effects of that plugin. Some ideas on how to do that:

* Set gravity to zero so we don't need buoyancy or a ground plane (that's similar to the Thruster tests added in #1190 )
* Apply forces / velocities directly to the vehicle without using extra plugins
* Measure the theoretical resulting velocities and accelerations based on the provided parameters

## Additional context

* This may be useful for #1247

**Comment by arjo129** [comment]
For further information purposes and future reference the following lecture notes provide the necessary steps for computing added mass of simple shapes
* http://web.mit.edu/2.016/www/handouts/Added_Mass_Derivation_050916.pdf
* https://ocw.mit.edu/courses/mechanical-engineering/2-016-hydrodynamics-13-012-fall-2005/readings/2005reading6.pdf
