### ISSUE TITLE
ThrusterPrivateData::ThrustToAngularVec ignores sign of thrust_coefficient

### ISSUE THREAD

**Issue by clydemcqueen** [gazebosim/gz-sim#1399]
## Environment
* OS Version: Ubuntu 20.04 
* Source or binary build? Source, main, latest commit = fc9cadd680e1414b38be71b404958aa8e16ff70d
  
  

## Description
* Expected behavior: clockwise (left-hand) thrusters should spin clockwise when thrust is positive, regardless of the value of  use_angvel_cmd.
* Actual behavior: when use_angvel_cmd is false the sign of thrust_coefficient is ignored. I traced this down to a bug in ThrustToAngularVec.

## Steps to reproduce

[Example model with balanced cw & ccw thrusters.](https://github.com/clydemcqueen/bluerov2_ignition/blob/4a107588bbb737dee66ed742ff2f76c0bb8e6c4b/models/bluerov2/model.sdf#L430)

Thruster 5 should be ccw and 6 should be cw. Note that use_angvel_cmd is false for both.

Sending these commands should result in constant downward thrust from thrusters 5 and 6. 5 should spin ccw and 6 should spin cw to balance out the torque:
```
ign topic -t /model/bluerov2/joint/thruster5_joint/cmd_thrust -m ignition.msgs.Double -p 'data: -9'
ign topic -t /model/bluerov2/joint/thruster6_joint/cmd_thrust -m ignition.msgs.Double -p 'data: -9'
```

The thrust values are correct, but both thrusters spin ccw. The torque does not balance, so the ROV frame rotates slightly.

I will send a 1-line PR.

**Comment by arjo129** [comment]
Looks like this was resolved.
