### ISSUE TITLE
Add ogre2 support in CI

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-sim#14]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gazebo/issues/14)) by Ian Chen (Bitbucket: [Ian Chen](https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/), GitHub: [iche033](https://github.com/iche033)).**

----------------------------------------
# Summary

Add ogre 2.1 dependency to CI systems

# Motivation

Some rendering tests are using `ogre` and we should start switching them to use `ogre2`. To do this, we need to first add ogre2.1 dependency to our CI systems otherwise the tests will fail with a warning msg about not being able to find the `ogre2` render engine.

**Comment by azeey** [comment]
I believe we have ogre2 in our CI now. Maybe not all platforms have it, but it might be better to open a more acute issue for such platforms.
