### ISSUE TITLE
README.md Installation Hyperlink deprecated

### ISSUE THREAD

**Issue by Nils-ChristianIseke** [gazebosim/gz-sim#1532]
The hyperlinks to the installationd documentation are deprecated, and should be updated. At the moment they are pointing to
https://ignitionrobotics.org/api/gazebo/6.0/install.html which returns a 404 Error.

**Comment by ahcorde** [comment]
Fixed here https://github.com/gazebosim/gz-sim/pull/1546

**Comment by ahcorde** [comment]
Feel free to reopen the issue if there are more broken links
