### ISSUE TITLE
Rendering sensors don't set SensorTopic

### ISSUE THREAD

**Issue by mjcarroll** [gazebosim/gz-sim#1541]
I noticed a bit of an inconsistency when implementing some MBZIRC functionality.

## Description
* Expected behavior: Other sensors such as the magnetometer and air pressure sensor set `gazebo::components::SensorTopic` component.  This allows the sensor topic to be retrieved by other consumers of the ECM.   Rendering sensors should be the same and set their respective topic component (or namespace in the case of multiple topics)

Example from Air Pressure sensor: https://github.com/gazebosim/gz-sim/blob/ign-gazebo6/src/systems/air_pressure/AirPressure.cc#L119

* Actual behavior: Rendering sensors do not set their SensorTopic component

## Implementation

The required information is likely available here: https://github.com/gazebosim/gz-sim/blob/ign-gazebo6/src/systems/sensors/Sensors.cc#L707-L708, but the ECM isn't available at that location.  It may need to be cached and retrieved for use in the next `PreUpdate` step.

**Comment by azeey** [comment]
Fixed by #1908
