### ISSUE TITLE
`Err: Unknown image format` while loading .tif for heightmap

### ISSUE THREAD

**Issue by jasmeet0915** [gazebosim/gz-sim#1628]
## Environment
* OS Version: Ubuntu 20.04 
* Binary, v6.10
  
  

## Description
* Expected behavior: Load .tif image as heightmap for terrain. 
* Actual behavior: `Image.cc` throws  `Unknown image format` error and does not load the image. The [script](https://github.com/gazebosim/gz-common/blob/d7266a3197ffc0876b54fac042412d78c4365816/graphics/src/Image.cc#L123) only checks for .PNG, .JPEG and .BMP formats and throws the above error other wise.
Tried including all the example dem models from: [https://app.gazebosim.org/search;q=dem](https://app.gazebosim.org/search;q=dem) but none of them work. Also tried creating a custom `.sdf` and creating a model using the `.tif` file as heightmap. 

## Steps to reproduce

1. Try including the DEM models from the above URL using `<include>` tags or download all the required images and create an `.sdf` file and open it with `ign gazebo`

## Output
![Screenshot from 2022-08-04 20-19-54](https://user-images.githubusercontent.com/23265149/182877580-5bf4a64b-57b2-4be4-af08-781e910012fc.png)

**Comment by chapulina** [comment]
DEM support is only available from Garden, i.e. Gazebo Sim 7.X. It will be released in the end of September.

https://gazebosim.org/docs/all/roadmap
