### ISSUE TITLE
Conveniently resize dimensions of objects

### ISSUE THREAD

**Issue by swarajpeppermint** [gazebosim/gz-sim#1690]
Resizing objects (especially standard objects like cylinder, capsule etc.) helps emulate different situations in simulations.
However, currently there's no clear way to resize an object in the simulator. Neither could I find any documentation to do the same in a quick internet search.
What is the current way of resizing an object in Ignition Gazebo, and can there be a simple straight forward way to do so (like there was in the legacy Gazebo)

**Comment by azeey** [comment]
@swarajpeppermint thanks for reporting the issue. I think this request is captured in https://github.com/gazebosim/gz-sim/issues/195, so I'll go ahead and close this.
