### ISSUE TITLE
Include collection name (eg. Fortress, Garden) along with the version

### ISSUE THREAD

**Issue by azeey** [gazebosim/gz-sim#1708]
## Desired behavior
The output of `gz sim --version` and the "About" dialog box currently only contain the version number, but users would find it more useful if they also contained the collection name since it's not easy to make the association between version numbers and the collection name without digging through the gazebosim website.

## Alternatives considered
n/a

## Implementation suggestion
This could be a CMake define so that it only needs to be updated in one place, in case if we need the name elsewhere.

## Additional context
Current dialog box:
![image](https://user-images.githubusercontent.com/206116/190261642-cba07045-4e92-4417-aee0-4b8bef1b3d84.png)

**Comment by ahcorde** [comment]
@azeey I checked that there is a CMake variable called `GZ_DISTRIBUTION`

![Selection_085](https://user-images.githubusercontent.com/1933907/195312152-cf0ffc3a-f55a-420d-acf2-d0422900d9b0.png)

![Selection_086](https://user-images.githubusercontent.com/1933907/195314473-cdf5a874-a47d-4c39-b93f-57ec1ac375f8.png)


PR https://github.com/gazebosim/gz-sim/pull/1756

**Comment by azeey** [comment]
Oh that's convenient!

**Comment by ahcorde** [comment]
PR is merged!
