### ISSUE TITLE
Partial wind effects configuration crashes the sim

### ISSUE THREAD

**Issue by hidmic** [gazebosim/gz-sim#1730]
## Environment
* OS Version: Ubuntu 20.04
* Source or binary build?
  Source, `gz-sim7`, https://github.com/gazebosim/gz-sim/commit/59b76c2d827cd928d27139a2ecd94f2a9a8d4de2 
  

## Description
* Expected behavior: partial `<force_approximation_scaling_factor>` configuration for `wind_effects` plugins such as:

```xml
<plugin
    filename="gz-sim-wind-effects-system"
    name="gz::sim::systems::WindEffects">
    <force_approximation_scaling_factor>
        <when zlt="8.0" zgt="-8.0" xlt="8.0" xgt="-8.0" ylt="-8.0" ygt="8.0">1</when>
    </force_approximation_scaling_factor>
</plugin>
```

* Actual behavior: simulation crashes when moving the object -->

![crash_ball](https://user-images.githubusercontent.com/13500507/191821038-d8b7cc71-0a7d-4b8b-9501-d4d8fc17bfce.gif)

**Comment by mjcarroll** [comment]
Closed by #1731
