### ISSUE TITLE
Touch Plugin Service Call Working but displaying `Service call timed out` msg

### ISSUE THREAD

**Issue by liamhan0905** [gazebosim/gz-sim#1745]
## Environment
* OS Version: Ubuntu 22.04 
* Source or binary build? Source `ign-gazebo6`, commit: aff92493203bdd72de7a85fa2f1c114f3d23c834
    
## Description
* Expected behavior: calling the service to reset the touch plugin should successfully go through
* Actual behavior: calling the service to reset the touch plugin causes `Service call timed out` even though the service actually goes through

## Steps to reproduce

1. open one terminal and type `ign topic -e -t /white_touches_only_green/touched`
2. click the play button and see the box fall. The touched topic will show as `true`
3. open another terminal and type 'ign service -s /white_touches_only_green/enable --reqtype ignition.msgs.Boolean --reptype ignition.msgs.Empty --timeout 300 --req 'data:true'`
3.calling the service will result another publication on the touched topic. This verifies that the service is working but for some reason we're getting a service timed out error

## Output

[Screencast from 09-30-2022 03:01:03 PM.webm](https://user-images.githubusercontent.com/44885838/193362230-49888943-fe90-470e-8fc6-41bf78914366.webm)

**Comment by azeey** [comment]
I've noticed that we get "Service call timed out" error for any service that has an `Empty` response type. It would be nice to resolve this since it affects other services as well
