### ISSUE TITLE
Distorted capsule geometry type on ignition gazebo fortress 6.12

### ISSUE THREAD

**Issue by Jakub-Krakowiak** [gazebosim/gz-sim#1769]
## Environment
* OS Version: Ubuntu 20.04
* Binary build, version 6.12
    - Rendering plugin: ogre2
      - [x] Sensor rendering error.
      - [x] GUI rendering error.
    - EGL headless mode:
      - [?] Running in EGL headless mode
      - [x] running on a dual GPU machine (integrated GPU + discrete GPU)
      - [ ] running on a multi-GPU machine (it has multiple discrete GPUs)
      - [x] running on real hardware
    - Rendering system info:
    - GPU: GTX970M driver version: 515.65.01

Capsule geometry looks severely distorted.
![2022-10-25_18-02](https://user-images.githubusercontent.com/108540924/197824247-f88c0b0a-ca50-44aa-bf18-0f5608e8a484.png)

## Description
* Expected behavior: Capsule geometry looks normal
* Actual behavior: Capsule geometry is distorted

## Steps to reproduce
Add an entity with capsule geometry to the scene, e.g. run ign gazebo shapes.sdf

**Comment by mjcarroll** [comment]
@j-rivero reproduced this locally for me.

**Comment by mjcarroll** [comment]
Closed by gazebosim/gz-common#475
