### ISSUE TITLE
System Plugin realTime not increasing while simulation is paused

### ISSUE THREAD

**Issue by Jakub-Krakowiak** [gazebosim/gz-sim#1777]
## Environment
* OS Version: Ubuntu 20.04 
* binary Fortress 6.12

When implementing a System Plugin realTime from info in functions PreUpdate and PostUpdate is not increasing when simulation is paused, opposite to what is said in the [documentation](https://gazebosim.org/api/sim/7/structgz_1_1sim_1_1UpdateInfo.html#a718958b8150697ade1fdfdf1b49f7eb3)
<img width="396" alt="RealTime" src="https://user-images.githubusercontent.com/108540924/199569860-192b6c90-2e86-4aae-9a0d-7ffc2564a4bc.png">

## Description
* Expected behavior: realTime increases when simulation is paused
* Actual behavior:  realTime does not increase when simulation is paused

## Steps to reproduce
1. Create a System Plugin e. g. using [your tutorial](https://gazebosim.org/api/sim/6/createsystemplugins.html)
2. implement PreUpdate or PostUpdate function as follows: 
<img width="723" alt="PostUpdate" src="https://user-images.githubusercontent.com/108540924/199569393-171fc2b6-a9d8-4a4b-9a75-4ae336e4dab1.png">

4. simulate a world with an entity e. g. world entity having this plugin active (and simulation paused)

## Output
<img width="206" alt="RealTimeNotChanging" src="https://user-images.githubusercontent.com/108540924/199569597-76d97d7b-8ea5-4e70-b402-9a87856ed17a.png">

**Comment by azeey** [comment]
The documentation seems to be incorrect/out-of-date. the `realTime` variable is used to measure the wall clock time elapsed while simulation is running. I've updated the docs in https://github.com/gazebosim/gz-sim/pull/1817
