### ISSUE TITLE
Fortress install docs not updated to state support for ubuntu 22 Jammy

### ISSUE THREAD

**Issue by Jakub-Krakowiak** [gazebosim/gz-sim#1795]
## Description
* Expected behavior: The whole doc states support for ubuntu 22 Jammy
* Actual behavior: The doc states future support for ubuntu 22 Jammy, while install doc states no support for ubuntu 22 Jammy.

## Evidence
From [Fortress Support](https://github.com/gazebo-tooling/release-tools/issues/596): 
<img width="604" alt="image" src="https://user-images.githubusercontent.com/108540924/201706579-de4dfcde-fffd-4c76-b2e4-4ca5e8008e90.png">

From [Fortress install doc](https://gazebosim.org/docs/fortress/install)

<img width="270" alt="image" src="https://user-images.githubusercontent.com/108540924/201707281-1e432a59-bcdb-4dcd-bb2b-264c85fc9df6.png">

From [Fortress ubuntu binary install](https://gazebosim.org/docs/fortress/install_ubuntu)
<img width="285" alt="image" src="https://user-images.githubusercontent.com/108540924/201708962-2b307b51-213b-41f2-bb22-523773b03f4e.png">

**Comment by j-rivero** [comment]
Thanks Jakub for the issue. I've create https://github.com/gazebosim/docs/pull/321 to update the documentation and also update the whole table in https://github.com/gazebo-tooling/release-tools/issues/596.

Please let me know if that syncs everything for you or I need to update any other place.
