### ISSUE TITLE
Garden/Fortress unable to read meshes from Fuel

### ISSUE THREAD

**Issue by ahcorde** [gazebosim/gz-sim#1828]
## Environment
* OS Version: Ubuntu 22.04
* Source 

When loading a world with tags from fuel Gazebo is crashing.

I can see these errors

```
[Err] [SDFFeatures.cc:320] Mesh construction from an SDF has not been implemented yet for dartsim.
[Err] [SDFFeatures.cc:787] The geometry element of collision [collision] couldn't be created
[Err] [SDFFeatures.cc:320] Mesh construction from an SDF has not been implemented yet for dartsim.
[Err] [SDFFeatures.cc:787] The geometry element of collision [collision] couldn't be created
[Err] [SDFFeatures.cc:320] Mesh construction from an SDF has not been implemented yet for dartsim.
[Err] [SDFFeatures.cc:787] The geometry element of collision [collision] couldn't be created
[Err] [SDFFeatures.cc:309] Heightmap construction from an SDF has not been implemented yet for dartsim.
[Err] [SDFFeatures.cc:787] The geometry element of collision [collision] couldn't be created
malloc(): invalid size (unsorted)
```

**Comment by mjcarroll** [comment]
The errors have already been reported and I addressed them here: https://github.com/gazebosim/gz-physics/pull/452

This fix was included in 6.2.0

The malloc is new/different, though.

**Comment by mjcarroll** [comment]
I confirmed that the error is still appearing so the pr mentioned above is not sufficient to fix the problem.

**Comment by azeey** [comment]
Do the Fuel models use the `fuel.ignitionrobotics.org` server? If so, it might be related to  https://github.com/gazebosim/gz-fuel-tools/pull/294#issuecomment-1281384267

**Comment by azeey** [comment]
@ahcorde says it might be due to issues on his local machine.

**Comment by 23pointsNorth** [comment]
Garden 7.6.0 still exhibits the same message on the terminal. Would additionally having a more descriptive error message be better? `The geometry element of collision [collision] couldn't be created` doesn't give much understanding to what entity in the tree this refers to.

**Comment by mavneo** [comment]
[Err] [SDFFeatures.cc:843] The geometry element of collision [collision] couldn't be created
same error still present, any updates on this, not all the model from fuel show this error, only few
