### ISSUE TITLE
JointPositionController not working for nested models

### ISSUE THREAD

**Issue by srmainwaring** [gazebosim/gz-sim#1844]
## Environment
* OS Version: macOS Monterey
* Source or binary build? Source: gz-sim7, 31f7d5b384408eb88db3fcc85cc5529eb926f069

## Description
* Expected behavior: The JointPositionController should control joints of nested models.
* Actual behavior: The nested joints do not respond to commands.

## Steps to reproduce

[test_nested_model.sdf.zip](https://github.com/gazebosim/gz-sim/files/10279011/test_nested_model.sdf.zip)

1. Run the Gazebo using the example world:

  ```bash
  gz sim -v4 -r test_nested_model.sdf
  ``` 

2. In a separate terminal issue commands to move the rotors:

  ```bash
  # Move rotor in model1
  gz topic -t "/rotor1_cmd" -m gz.msgs.Double -p "data: 1"

  # Move rotor in model2 (nested)
  gz topic -t "/rotor2_cmd" -m gz.msgs.Double -p "data: 1"

  # Move rotor in model3
  gz topic -t "/rotor3_cmd" -m gz.msgs.Double -p "data: 1"
  ``` 

## Output

The single yellow block is model1, the teal block is model3 and the yellow block attached to the teal block is model2 which is nested in model3.  The rotors in the top level models (model1 and model2) both move. The rotor in the nested model (model2) does not respond.

![nested-joint-pos-ctrl](https://user-images.githubusercontent.com/24916364/208944117-b6fcc9d3-6c32-446b-874b-1ec224a709b1.png)

When stepping through the joint controller plugin the `JointPositionController::PreUpdate` returns at L268 because `jointPosComp->Data()` is always empty for the nested joints.

https://github.com/gazebosim/gz-sim/blob/31f7d5b384408eb88db3fcc85cc5529eb926f069/src/systems/joint_position_controller/JointPositionController.cc#L267-L268 

Server log:

```bash
gz sim -v4 -s -r test_nested_model.sdf
[Msg] Gazebo Sim Server v7.1.0
[Msg] Loading SDF world file[/Users/rhys/Code/ardupilot/simulation/ardupilot_gazebo/worlds/test_nested_model.sdf].
[Msg] Serving entity system service on [/entity/system/add]
[Dbg] [Physics.cc:869] Loaded [gz::physics::dartsim::Plugin] from library [/Volumes/MacPro2_DV1/Code/osrf/gz_garden_ws/install/lib/gz-physics-6/engine-plugins/libgz-physics-dartsim-plugin.dylib]
[Dbg] [SystemManager.cc:71] Loaded system [gz::sim::systems::Physics] for entity [1]
[Msg] Create service on [/world/test_nested_model/create]
[Msg] Remove service on [/world/test_nested_model/remove]
[Msg] Pose service on [/world/test_nested_model/set_pose]
[Msg] Pose service on [/world/test_nested_model/set_pose_vector]
[Msg] Light configuration service on [/world/test_nested_model/light_config]
[Msg] Physics service on [/world/test_nested_model/set_physics]
[Msg] SphericalCoordinates service on [/world/test_nested_model/set_spherical_coordinates]
[Msg] Enable collision service on [/world/test_nested_model/enable_collision]
[Msg] Disable collision service on [/world/test_nested_model/disable_collision]
[Msg] Material service on [/world/test_nested_model/visual_config]
[Msg] Material service on [/world/test_nested_model/wheel_slip]
[Dbg] [SystemManager.cc:71] Loaded system [gz::sim::systems::UserCommands] for entity [1]
[Dbg] [SystemManager.cc:71] Loaded system [gz::sim::systems::SceneBroadcaster] for entity [1]
[Dbg] [JointPositionController.cc:205] [JointPositionController] system parameters:
[Dbg] [JointPositionController.cc:206] p_gain: [2]
[Dbg] [JointPositionController.cc:207] i_gain: [0.1]
[Dbg] [JointPositionController.cc:208] d_gain: [0.01]
[Dbg] [JointPositionController.cc:209] i_max: [1]
[Dbg] [JointPositionController.cc:210] i_min: [-1]
[Dbg] [JointPositionController.cc:211] cmd_max: [1000]
[Dbg] [JointPositionController.cc:212] cmd_min: [-1000]
[Dbg] [JointPositionController.cc:213] cmd_offset: [0]
[Dbg] [JointPositionController.cc:214] Topic: [rotor1_cmd]
[Dbg] [JointPositionController.cc:215] initial_position: [0]
[Dbg] [SystemManager.cc:71] Loaded system [gz::sim::systems::JointPositionController] for entity [8]
[Dbg] [JointPositionController.cc:205] [JointPositionController] system parameters:
[Dbg] [JointPositionController.cc:206] p_gain: [2]
[Dbg] [JointPositionController.cc:207] i_gain: [0.1]
[Dbg] [JointPositionController.cc:208] d_gain: [0.01]
[Dbg] [JointPositionController.cc:209] i_max: [1]
[Dbg] [JointPositionController.cc:210] i_min: [-1]
[Dbg] [JointPositionController.cc:211] cmd_max: [1000]
[Dbg] [JointPositionController.cc:212] cmd_min: [-1000]
[Dbg] [JointPositionController.cc:213] cmd_offset: [0]
[Dbg] [JointPositionController.cc:214] Topic: [rotor3_cmd]
[Dbg] [JointPositionController.cc:215] initial_position: [0]
[Dbg] [SystemManager.cc:71] Loaded system [gz::sim::systems::JointPositionController] for entity [16]
[Dbg] [JointPositionController.cc:205] [JointPositionController] system parameters:
[Dbg] [JointPositionController.cc:206] p_gain: [2]
[Dbg] [JointPositionController.cc:207] i_gain: [0.1]
[Dbg] [JointPositionController.cc:208] d_gain: [0.01]
[Dbg] [JointPositionController.cc:209] i_max: [1]
[Dbg] [JointPositionController.cc:210] i_min: [-1]
[Dbg] [JointPositionController.cc:211] cmd_max: [1000]
[Dbg] [JointPositionController.cc:212] cmd_min: [-1000]
[Dbg] [JointPositionController.cc:213] cmd_offset: [0]
[Dbg] [JointPositionController.cc:214] Topic: [rotor2_cmd]
[Dbg] [JointPositionController.cc:215] initial_position: [0]
[Dbg] [SystemManager.cc:71] Loaded system [gz::sim::systems::JointPositionController] for entity [25]
[Msg] Loaded level [3]
[Msg] Serving world controls on [/world/test_nested_model/control], [/world/test_nested_model/control/state] and [/world/test_nested_model/playback/control]
[Msg] Serving GUI information on [/world/test_nested_model/gui/info]
[Msg] World [test_nested_model] initialized with [1ms] physics profile.
[Msg] Serving world SDF generation service on [/world/test_nested_model/generate_world_sdf]
[Msg] Serving world names on [/gazebo/worlds]
[Msg] Resource path add service on [/gazebo/resource_paths/add].
[Msg] Resource path get service on [/gazebo/resource_paths/get].
[Msg] Resource path resolve service on [/gazebo/resource_paths/resolve].
[Msg] Resource paths published on [/gazebo/resource_paths].
[Msg] Server control service on [/server_control].
[Msg] Found no publishers on /stats, adding root stats topic
[Msg] Found no publishers on /clock, adding root clock topic
[Dbg] [SimulationRunner.cc:508] Creating PostUpdate worker threads: 2
[Dbg] [SimulationRunner.cc:519] Creating postupdate worker thread (0)
[Err] [SDFFeatures.cc:1077] Asked to create a joint between links [base2_link] as parent and [rotor2_link] as child, but the child link already has a parent joint of type [RevoluteJoint].
[Msg] Serving scene information on [/world/test_nested_model/scene/info]
[Msg] Serving graph information on [/world/test_nested_model/scene/graph]
[Msg] Serving full state on [/world/test_nested_model/state]
[Msg] Serving full state (async) on [/world/test_nested_model/state_async]
[Msg] Publishing scene information on [/world/test_nested_model/scene/info]
[Msg] Publishing entity deletions on [/world/test_nested_model/scene/deletion]
[Msg] Publishing state changes on [/world/test_nested_model/state]
[Msg] Publishing pose messages on [/world/test_nested_model/pose/info]
[Msg] Publishing dynamic pose messages on [/world/test_nested_model/dynamic_pose/info]
[Dbg] [EntityComponentManager.cc:1619] Updated state thread iterators: 32 threads processing around 2 entities each.
```

The error:

```bash
[Err] [SDFFeatures.cc:1077] Asked to create a joint between links [base2_link] as parent and [rotor2_link] as child, but the child link already has a parent joint of type [RevoluteJoint].
```

Suggests that the physics engine may be attempting to build the nested model twice?

## Related

The same issue is observed when composing models using the `<include>` element.

**Comment by srmainwaring** [comment]
## Investigations

Work in progress trying to tack down the origin of the issue. Notes below.

- The issue, as far as the `gz-sim` physics plugin is concerned, appears to be that the nested joints are not in the Physics plugin's `entityJointMap`.
- The cause of this occurs at a lower level in the dart physics engine, somewhere in `gz::physics::dartsim::EntityManagementFeatures` where the nested joint is not found in the call to `GetJoint`. Possibly because this does not recurse down to nested models or for some other reason?

#### Notes

1. `gz::sim::systems:: PhysicsPrivate:: CreateModelEntities`

There are two places where nested models are constructed. The first for models that are direct children of the world: 

https://github.com/gazebosim/gz-sim/blob/31f7d5b384408eb88db3fcc85cc5529eb926f069/src/systems/physics/Physics.cc#L1123-L1124

and the second for models that are not (and so must be nested):

https://github.com/gazebosim/gz-sim/blob/31f7d5b384408eb88db3fcc85cc5529eb926f069/src/systems/physics/Physics.cc#L1175

The first call will construct models recursively, so that when the second call is made the nested model is already constructed.

2. `gz::sim::systems::PhysicsPrivate::CreateJointEntities`

For the non-nested joints, the function `CreateJointEntities` hits the test if they already exist, and proceeds to insert them into the `entityJointMap`:

https://github.com/gazebosim/gz-sim/blob/31f7d5b384408eb88db3fcc85cc5529eb926f069/src/systems/physics/Physics.cc#L1680-L1689

For the nested joints this test fails (which is odd because we see below there is an error message reporting the joint already exists). In any case the function continues until it hits:

https://github.com/gazebosim/gz-sim/blob/31f7d5b384408eb88db3fcc85cc5529eb926f069/src/systems/physics/Physics.cc#L1723-L1734

where the test for a valid physics pointer to a joint fails and the the inserting of the joint into the `entityJointMap` is skipped. To see why the attempt to create the joint failed we need to look into `ConstructSdfJoint`.

3. `gz::physics::dartsim::SDFFeatures::ConstructSdfJoint`

The attempt to create the nested joint fails here:

[gz-physics6/dartsim/src/SDFFeatures.cc#L1074-L1083](https://github.com/gazebosim/gz-physics/blob/2a93515f7995a8a060d62acd93c88294e4cae65f/dartsim/src/SDFFeatures.cc#L1074-L1083)
```c++
    auto childsParentJoint = _child->getParentJoint();
    if (childsParentJoint->getType() != "FreeJoint")
    {
      gzerr << "Asked to create a joint between links "
             << "[" << _parent->getName() << "] as parent and ["
             << _child->getName() << "] as child, but the child link already "
             << "has a parent joint of type [" << childsParentJoint->getType()
             << "].\n";
      return this->GenerateInvalidId();
    }
```

because the joint has already been associated with a link, but for some reason is not recorded in the dart physics plugin as an existing link when queried using the entity management feature `GetJointFromModel`. So that's where to look next.

**Comment by azeey** [comment]
Thanks for sleuthing @srmainwaring. I'm wondering if this is a regression from #1560 or something that existed all along.

**Comment by srmainwaring** [comment]
> I'm wondering if this is a regression from #1560 or something that existed all along

I think it was around before then. I rolled back gz-sim to the commit before #1560 and the issue remained.

I'm slowly zeroing in on possible causes - I suspect it may either be a recursion thing - where the dart model only reports its immediate child joints, or there is a double entry of the nested joint into the `Base::AddJoint` and one of them is not connected up to anything. It's a little daunting navigating through the type lists but I'm getting there...

**Comment by srmainwaring** [comment]
@azeey - the issue arises in the function `ConstructSingleAxisJoint` in `SDFFeatures ` where the joints from the nested model are reassigned to the container model. In the notes above, I've including a link to a fork containing some debug code for `Base.hh` to print the contents of the EntityStore as these are difficult to inspect in a debugger directly.

It's not clear to me what the correct fix is - any change is going to have knock on effects elsewhere. Options seem to be:

1. Don't reassign joints to the parent entity for nested models.
2. Continue to reassign them and update the search functions to resolve joints for nested models as though they were not reassigned.

I don't think Option 2 is a good choice - it would be very confusing and almost impossible to maintain (tracing the model state is quite difficult as it is). That leaves option 1, but I'm not familiar with DART to know how the object model will cope with this type of nesting.

**Comment by srmainwaring** [comment]
I've started a fix for this. The branches will probably change as I tidy things up and remove debug code but currently the changes are here:

- https://github.com/srmainwaring/gz-physics/tree/srmainwaring/6/1844-joint-pos-nested-models
- https://github.com/srmainwaring/gz-sim/tree/srmainwaring/7/joint-pos-controller

The main changes are broken down as follows:

#### `gz-physics`

- [ ] Update `EntityManagementFeatures::GetJoint` to search recursively up to the top-level containing model for a named joint (or joint by index), as the joints are moved to the container body nodes as the skeleton is assembled. [gz-physics: b9b3ffd](https://github.com/srmainwaring/gz-physics/commit/b9b3ffd552f3c91df519c37f88a3fc7ebb9a7acc)

#### `gz-sim`

- [ ]  Update the `JointPositionController` to search using both scoped and unscoped joint names.  [gz-sim: 61bca3d](https://github.com/srmainwaring/gz-sim/commit/61bca3d5ffaf4079caee5f70158ed8f6ef89f766)
### Outstanding issues

- [ ] ECM Entity Id is not correctly mapped to Physics Id when the container and nested model contain joints with the same unscoped name.
- [ ] Joints between two nested models are not resolved correctly.

**Comment by srmainwaring** [comment]
@azeey this should still be open as it requires https://github.com/gazebosim/gz-sim/pull/1851 to be merged as well.
