### ISSUE TITLE
Ackermann plugin turningRadius bug when linVel is zero

### ISSUE THREAD

**Issue by bperseghetti** [gazebosim/gz-sim#1848]
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build?
  binary, ignition-fortress

## Description
* Expected behavior: With Ackerman plugin wheels should point direction of steering when having no forward commanded velocity.
* Actual behavior: Wheels always rotate clockwise when linVel is zero.
## Steps to reproduce
Run MR-Buggy3 with teleop and command it to yaw right (they only point left)

## Output

https://user-images.githubusercontent.com/10233412/209772618-b0a06ad2-28dd-4d53-988e-22d568f7209f.mp4

**Comment by jennuine** [comment]
Fixed in https://github.com/gazebosim/gz-sim/pull/1849
