### ISSUE TITLE
HOW CAN I SUBSCRIBE ROS TOPIC IN IGNITION TRANSPORT 

### ISSUE THREAD

**Issue by omr-web** [gazebosim/gz-sim#1880]
Hello everyone, I need your help a lot. I am using the Ignition-Garden version of Gazebo. What I want to do is this:
To subscribe to a topic published in ROS2 using the transport communication in the ignition gazebo. My process steps are as follows:
1) Publishing float messages over ROS2
2) Using ROS Bridge to make the message appear in the gazebo.
3) To subscribe with the Subscribe function in Transport communication.
I do the first two steps without any problems. When I type ign topic -e -t /foo, I can echo the /foo topic published on ros2. But the code I wrote using transport communication does not subscribe.

I can subscribe to the topic published by the publisher code I wrote using the transport communication structure. So I think my subscribe code is correct.

I share my codes. 
Thank you your help.

## Publisher.h

```
#include <chrono>
#include <functional>
#include <memory>
#include <string>

#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/string.hpp"
#include "std_msgs/msg/float32.hpp"
#include "geometry_msgs/msg/twist.hpp"
using namespace std::chrono_literals;

class VelocityPublisher : public rclcpp::Node
{
public:
    VelocityPublisher() : Node("VelocityPublisher")
    {
        publisher_ = this->create_publisher<std_msgs::msg::Float32>("foo", 10);
        timer_ = this->create_wall_timer(1000ms, std::bind(&VelocityPublisher::VelocityTimer, this));
    }
    void VelocityTimer();
    rclcpp::TimerBase::SharedPtr timer_;
    rclcpp::Publisher<std_msgs::msg::Float32>::SharedPtr publisher_;
    geometry_msgs::msg::Twist veri;
    std_msgs::msg::Float32 float_veri;
};
```
## Publisher.cpp
```
#include "velocity_publisher.h"

void VelocityPublisher::VelocityTimer()
{
  // veri.linear.x=500;
  // veri.linear.y=500;
  // veri.linear.z=500;
  // publisher_->publish(veri);

  float_veri.data = 20;
  publisher_->publish(float_veri);
  std::cout << "yayinlandi" << std::endl;
}

int main(int argc, char *argv[])
{
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<VelocityPublisher>());
  rclcpp::shutdown();
  return 0;
}
```
## Subscriber.cpp

```
#include <iostream>
#include <string>
// #include <ignition/msgs.hh>
// #include <ignition/transport.hh>
#include <gz/transport/Node.hh>
#include <gz/msgs.hh>
//////////////////////////////////////////////////
/// \brief Function called each time a topic update is received.
void cb(const gz::msgs::Float &_msg)
{
  std::cout << "Callback: " << std::endl;
}

//////////////////////////////////////////////////
int main(int argc, char **argv)
{
  std::cout << "hello ";

  gz::transport::Node node;
  std::string topic = "/foo";

  // Subscribe to a topic by registering a callback.
  if (!node.Subscribe(topic, cb))
  {
    std::cerr << "Error subscribing to topic [" << topic << "]" << std::endl;
    return -1;
  }

  // Zzzzzz.
  gz::transport::waitForShutdown();
  return 0;
}

```
I use this command for ros2 bridge :

`ros2 run ros_gz_bridge parameter_bridge /foo@std_msgs/msg/Float32]ignition.msgs.Float`

**Comment by azeey** [comment]
@omr-web this is a question best suited for answers.gazebosim.org or robotics.stackexchange.com. Could you please post your question there?

 I'll close this issue since this doesn't appear to be a bug.
