### ISSUE TITLE
Atmosphere Type

### ISSUE THREAD

**Issue by omr-web** [gazebosim/gz-sim#1900]
I want to change atmosphere type. Default type is adiabatic. what is the types of atmosphere in ignition gazebo?

thank you your replies.

**Comment by mjcarroll** [comment]
Currently, the only supported atmosphere type that I'm aware of is `adiabatic` according to the sdformat speification: http://sdformat.org/spec?ver=1.9&elem=world#world_atmosphere

**Comment by omr-web** [comment]
I understand thank you.
