### ISSUE TITLE
Multicopter MotorModel Plugin and PID Controller for UAV in ROS2

### ISSUE THREAD

**Issue by omr-web** [gazebosim/gz-sim#1903]
hello everyone,
I am making an altitude and attitude controller for an unmanned aerial vehicle (UAV, drone) with Ignition Gazebo and ROS2. I use the multicopter motor model plugin to do this. I would like your help with an interesting situation I encountered: 
When I give the command to go up to my model (drone) with the joystick, the model goes up and hover in the air as I expected. But all of a sudden the model falls to the ground. The model does not move upwards even if I send the ascend command. I think this situation is not caused by the controller I wrote. I would like to explain the reason for this graphically:

https://drive.google.com/file/d/178Reu0bQNrdhItp2T65bAHIVXn2gucPa/view?usp=sharing

Above are two graphs with the same x-axis. In the graphic above, there are the target distance (setpoint), the location (measured) and the difference between the setpoint and the measured (error) for the model to go, and the velocity values ​​to go to the motors produced by the altitude controller in the graphic at the bottom. When the red graph is examined, while the controller is working correctly, that is, the model with reduced error reaches the desired (setpoint) position and drops down at a time. 

When the controller graphic is examined at first, it seems to work properly, because as the error decreases (blue line in the upper graph), the velocity value that will go to the produced motors decreases. so I think the source of the problem is not the controller, but the gazebo world. Is there a factor in the gazebo world that I should pay attention to? For example, type of atmosphere, air pressure etc.

I changed the pid coefficients in the attitude controller. I observed that when the coefficients are 0, that is, when the attitude controller is disabled, the model hover in the air and falls suddenly again. The reason I disabled the Attitude controller was the possibility that the pid results produced by this attitude controller could be dropping the model while it was hovering. 

this is the link of the simulation video:
https://drive.google.com/file/d/1-wcMwoHd61y1bFJst3OIfsTULB25UVhP/view?usp=sharing

Thank you for your help,
Kind regards.

**Comment by azeey** [comment]
@omr-web this is a question best suited for answers.gazebosim.org or robotics.stackexchange.com since it doesn't appear to be a bug/feature request on gz-sim. Could you please post your question there?

**Comment by vbalaji21** [comment]
I am curious on this question and answer. If it is solved can you please let me know, how it is solved. If the question is asked in robotics stack exchange, share the link here.

**Comment by aarsht7** [comment]
Hello @azeey 

I faced a similar issue with gzsim. I have asked the [question on the roobtics se](https://robotics.stackexchange.com/questions/115587/gzsim-drone-crashes-after-certain-time-of-flight). Will it be possible for you to have a look whenever you get some time?

Thanks!
