### ISSUE TITLE
:farmer: Flaky test `INTEGRATION_ackermann_steering_system` on gz-gazebo3 and gz-gazebo6

### ISSUE THREAD

**Issue by Crola1702** [gazebosim/gz-sim#1993]
## Environment
* OS Version: Ubuntu Focal, Homebrew 
* Source gz-gazebo3 and gz-gazebo6 latest

## Description
* Expected behavior: `INTEGRATION_ackermann_steering_system` test should pass
* Actual behavior: `INTEGRATION_ackermann_steering_system` is failing sometimes

## Steps to reproduce
1. Run a build in in one of the following jobs ([gazebo3-homebrew](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo3-homebrew-amd64/), [gazebo3-focal](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo3-focal-amd64/),  [gazebo6-homebrew](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo6-homebrew-amd64/), [gazebo6-focal](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo6-focal-amd64/))
2. See test fail (if lucky)

## Output

Reference build: https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo3-homebrew-amd64/290/

Log output (INTEGRATION_ackermann_steering_system):

```
57: [Dbg] [EntityComponentManager.cc:643] Using components of type [14423792621074650228] / [ign_gazebo_components.JointVelocityCmd].
57: [Dbg] [EntityComponentManager.cc:643] Using components of type [9436740692853731264] / [ign_gazebo_components.JointPosition].
57: /Users/jenkins/jenkins-agent/workspace/ignition_gazebo-ci-ign-gazebo3-homebrew-amd64/ign-gazebo/test/integration/ackermann_steering_system.cc:422: Failure
57: Expected equality of these values:
57:   odomPoses.size()
57:     Which is: 3
57:   tfPoses.size()
57:     Which is: 2
57: [Dbg] [SimulationRunner.cc:533] Exiting postupdate worker thread (1)
57: [Dbg] [SimulationRunner.cc:533] Exiting postupdate worker thread (0)
57: [  FAILED  ] ServerRepeat/AckermannSteeringTest.TfPublishes/0, where GetParam() = 1 (889 ms)
```

#### Statistics for the last 2 months:

|job_name|last_time|first_time|build_count|failure_count|failure_percentage|
| -- | -- | -- | -- | -- | -- |
|ignition_gazebo-ci-ign-gazebo3-homebrew-amd64|2023-05-10|2021-04-23|12|1|8.33 %|
|ignition_gazebo-ci-ign-gazebo3-focal-amd64|2023-05-10|2022-01-05|20|2|10.0 %|
|ignition_gazebo-ci-ign-gazebo6-homebrew-amd64|2023-05-08|2021-09-29|12|3|25.0 %|
|ignition_gazebo-ci-ign-gazebo6-focal-amd64|2023-05-05|2022-01-05|19|3|15.79 %|

**Comment by claraberendsen** [comment]
@azeey was the fix in #1989 ported to ign-gazebo3? 
We started seeing this again sporadically in ign-gazebo-3
 - Build 323 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo-ci-ign-gazebo3-homebrew-amd64&build=323)](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo3-homebrew-amd64/323/)
 - Build 321 [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_gazebo-ci-ign-gazebo3-homebrew-amd64&build=321)](https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo3-homebrew-amd64/321/)
