### ISSUE TITLE
Joint Position Controller Bug with multiple entities.

### ISSUE THREAD

**Issue by BA-Utkarsh** [gazebosim/gz-sim#2099]
## Environment
* OS Version: Ubuntu 22.04.2 LTS

## Description
- Included the Joint Position Controller plugin in our example.
- Found out that while clicking on multiple entities the list gets appended and doesn't get clear for the previous entity.

## Actual behavior:
- Clicked on L_0, we see `pan_joint` `tilt_joint` and `roll_joint`
![L_0_Clicked_bug](https://github.com/gazebosim/gz-sim/assets/80967869/316b3c0a-0499-4c4a-9b35-a755897a5c10)
- Clicked on L_1, we see additional `pan_joint` `tilt_joint` and `roll_joint` are added.
![L_1_Clicked_bug](https://github.com/gazebosim/gz-sim/assets/80967869/4a31b854-dc53-488e-860f-3cf5d75e8740)

- **They are duplicates. And sliders are not working properly.**
- **If we clicked on all the entities, the list gets appending and sliders doesn't work properly.**

## Expected behavior:
- Expectation is, the previous entity should be cleared out.
- Clicked on L_0, we see `pan_joint` `tilt_joint` and `roll_joint` for L_0 only.
![L_0_Clicked](https://github.com/gazebosim/gz-sim/assets/80967869/bb2e0c8f-d55d-4abb-b642-27c3b16c715b)
- Clicked on L_2, we see `pan_joint` `tilt_joint` and `roll_joint` for L_2 only.
![L_2_Clicked](https://github.com/gazebosim/gz-sim/assets/80967869/9794ffcd-f130-45dd-91ae-d2af6691348c)

## Steps to reproduce
- We have created the minimal testcase which has 4 Logical Cameras (L_0, L_1, L_2 and L_3) with Joint Position Controller.
* Untar the zip file.  
  $ unzip [JPC_bug_testcase.zip](https://github.com/gazebosim/gz-sim/files/12473307/JPC_bug_testcase.zip)
```
Archive:  JPC_bug_testcase.zip
   creating: LogCamera/
  inflating: LogCamera/model.config
  inflating: LogCamera/model.sdf
  inflating: minimal_JPC_bug.sdf
```
* Source the gazebo path.
  $ source /opt/gazebo/install/setup.bash
* Export the model path.  
  $ export GZ_SIM_RESOURCE_PATH="$PWD:/opt/gazebo/models"
* Run.  
  $ gz sim ./minimal_JPC_bug.sdf

## Proposal
- From `steps to reproduce`, we reproduced the actual behavior.
- However, we have made the fix by [JPC_bug_fix.patch](https://github.com/gazebosim/gz-sim/files/12473373/JPC_bug_fix.patch)
- From above patch we can see the expected behavior.

**Let us know your valuable inputs on the same.**

**Comment by iche033** [comment]
thanks for the patch. I can confirm that it fixes the bug. I've created https://github.com/gazebosim/gz-sim/pull/2101 based on the patch

**Comment by BA-Utkarsh** [comment]
Thank you for the support @iche033
