### ISSUE TITLE
Particle emittor incorrect colour

### ISSUE THREAD

**Issue by jrutgeer** [gazebosim/gz-sim#2117]
## Environment
* OS Version: Ubuntu 22.04
* Garden, source built
* Ogre2

## Description

Run particle emittor demo world:

`$ gz sim particle_emitter.sdf`

The fog looks correct but the 'bright red´ particles are black. There are red 'flashes' that lead me to assume that the particle is initially created in red, but on a successive render call is rendered black.

https://github.com/gazebosim/gz-sim/assets/74099146/c8aff570-1af3-42c4-aef6-53f935fe6fb3

**Comment by iche033** [comment]
https://github.com/gazebosim/gz-rendering/pull/903 should fix the color issue for this demo. Ticketed a separate issue to track the root cause of this issue in https://github.com/gazebosim/gz-rendering/issues/902
