### ISSUE TITLE
Elevator state is not being publish on the ground floor

### ISSUE THREAD

**Issue by Voldivh** [gazebosim/gz-sim#2153]
## Environment
* OS Version: Ubuntu Jammy
* Source and Binary

## Description
* Expected behavior: The elevator should publish a message to it's `state` topic on each floor it is in.
* Actual behavior: The elevator publish a message for all floors except the ground floor.

## Steps to reproduce

1. Run the elevator.sdf file:
```bash
gz sim elevator.sdf
```
2. Subscribe to the elevator state:
```bash
gz topic -e -t /model/elevator/state
```
3. Publish a floor for the elevator to go. Example:
```bash
gz topic -t "/model/elevator/cmd" -m gz.msgs.Int32 -p "data: 2"
```

## Output
We get the expected behavior when we send the elevator to any of the upper floors:
![image](https://github.com/gazebosim/gz-sim/assets/51831786/862f27a0-63b1-4368-8b9c-dc07cc042821)
However, when we send the elevator to the ground floor (`gz topic -t "/model/elevator/cmd" -m gz.msgs.Int32 -p "data: 0"`), we stop receiving information on the console:
![image](https://github.com/gazebosim/gz-sim/assets/51831786/f523921e-3e05-4e51-aada-51253b3a3744)

**Comment by Voldivh** [comment]
Interesting. I don't think it is critical to be able to echo it as long as the we still get the correct value on the subscription. My only concern is that it may confuse users that are not aware of that specific behavior. Maybe we could add a little comment at the top of the .sdf file? I can go ahead and create the appropriate PR if you agree on the "solution".

**Comment by mjcarroll** [comment]
I think a comment would be helpful.

Or we can 1-index all of our arrays from now on. :wink:

**Comment by Voldivh** [comment]
I agree, let's go with the comment for now and keep it in mind from now on.
