### ISSUE TITLE
Removing model with `JointPositionController` plugin leads to 'entity does not exist' error messages.

### ISSUE THREAD

**Issue by jrutgeer** [gazebosim/gz-sim#2165]
When a model that uses the `JointPositionController` plugin is removed from the simulation through the UserCommands service, repeating error messages appear:

```
[Err] [EntityComponentManager.cc:1083] Trying to create a component of type [8319580315957903596] attached to entity [12], but this entity does not exist. This create component request will be ignored.
```

See the attached example files:

Run `gz sim -r world.sdf`
Spawn a model with the spawn script: `./spawn_boxes`
Remove the boxes with the remove script: `./remove_boxes`

--> The error messages start.

Edit the `boxes.sdf` file and remove the `JointPositionController` plugin.
Repeat the test.

--> No error messages after removal.

[example.tar.gz](https://github.com/gazebosim/gz-sim/files/12704007/example.tar.gz)

**Comment by arjo129** [comment]
I think if we solve #2217 this will no longer be an issue.

**Comment by jrutgeer** [comment]
Closing as duplicate of https://github.com/gazebosim/gz-sim/issues/2217.
