### ISSUE TITLE
:woman_farmer: Segfault on `INTEGRATION_save_world.test_ran` gz-sim windows 6, 7 and 8

### ISSUE THREAD

**Issue by claraberendsen** [gazebosim/gz-sim#2177]
## Environment
* OS Version: 
Windows
* Source or binary build?
 **Reference build**: https://build.osrfoundation.org/job/ign_gazebo-gz-8-win/14/
<details>

</details>

## Description
* Expected behavior: 
All gz-sim test to complete 
* Actual behavior: 
`INTEGRATION_save_world.test_ran` fails with segfault,
```
211: [ RUN      ] SdfGeneratorFixture.WorldWithRenderingSensors
211: Loading: C:\J\workspace\ign_gazebo-gz-8-win\ws\gz-sim\test\worlds\sensor.sdf
211/246 Test #211: INTEGRATION_save_world .................................***Exception: SegFault  4.38 sec
test 212
```

## Output

This failed on the first time on this job on https://build.osrfoundation.org/job/ign_gazebo-gz-8-win/3/.  However this is test is known to be flaky (see #1175) for an example. 
Failing 22.22% in 2 out of 9 builds

**Comment by Crola1702** [comment]
Last 15 days flaky ratio (11/10/2023):

job_name|last_fail|first_fail|build_count|failure_count|failure_percentage
--|--|--|--|--|--
ign_gazebo-gz-8-win|2023-10-10|2023-09-28|6|2|33.33
ign_gazebo-gz-7-win|2023-10-10|2023-10-07|8|2|25.0
ign_gazebo-ign-6-win|2023-10-01|2023-10-01|5|1|20.0



Updated title to match all gz-sim versions that contain this problem.
