### ISSUE TITLE
Ignition Fortress 6.15.0 does not display magnetic field or gravity data.

### ISSUE THREAD

**Issue by victorcarvesk** [gazebosim/gz-sim#2192]
## Environment
* OS Version: Ubuntu 22.04.3 LTS 
* Source or binary build? Binary
  
  

Hi. I'm developing an AHRS sensor on the Ignition Fortress and noticed that my interface doesn't display magnetic field or gravity data. I installed other versions (Garden and Harmonic) and everything works fine in them.
Is there anything I can do to make this data displayed?

![Screenshot from 2023-10-05 08-36-07](https://github.com/gazebosim/gz-sim/assets/73046510/fc226714-6266-4563-9f9e-282aabe08ffc)

**Comment by iche033** [comment]
#2195 should fix the issue.

**Comment by azeey** [comment]
Closed by #2195
