### ISSUE TITLE
Requesting scene state fails from the same process as Server

### ISSUE THREAD

**Issue by shameekganguly** [gazebosim/gz-sim#2194]
Requesting ECM state from the state service at `/world/default/state` from the same process that is running the `Server` always fails. See the following snippet for example:
```
gz::sim::ServerConfig server_config;
const std::string sdf_path = "sphere.sdf";
server_config.SetSdfFile(sdf_path);
gz::sim::Server server(server_config);
server.Run(/*_blocking=*/false);

absl::SleepFor(absl::Seconds(5));

const std::string service_name = "/world/default/state";

gz::transport::Node node;
gz::msgs::SerializedStepMap reply;
std::cout << "Request state" << std::endl;
bool request_success = false;
if (!node.Request(service_name, 10000 /*timeout in ms*/, reply,
                  request_success)) {
  std::cerr << "Failed to request state, transport failure" << std::endl;
}
if (!request_success) {
  std::cerr << "Failed to request state, server failure" << std::endl;
}
```
for a simple sdf file which has a sphere and the physics and scene broadcaster plugins, will fail with `Failed to request state, server failure`.

The server log indicates that the `SceneBroadcaster` system postupdate was blocked on the condition variable here:
https://github.com/gazebosim/gz-sim/blob/f6efeefb4ab99284d1a053061235f8c2fa02a5da/src/systems/scene_broadcaster/SceneBroadcaster.cc#L735, since I see the following logs:
```
E1006 00:34:55.367637 2449457 SceneBroadcaster.cc:733] Timed out waiting for state
Failed to request state, server failure
I1006 00:34:55.368184 2450517 EntityComponentManager.cc:1624] Updated state thread iterators: 11 threads processing around 1 entities each.
W1006 00:34:55.368694 2450547 Model.hh:69] Skipping serialization / deserialization for models with //pose/@relative_to attribute.
W1006 00:34:55.369067 2450554 Component.hh:144] Trying to serialize component with data type [N3sdf2v05WorldE], which doesn't have `operator<<`. Component will not be serialized.
```

**Comment by iche033** [comment]
Would the non-blocking version of `Request` work for you? [example usage](https://github.com/gazebosim/gz-sim/blob/f6efeefb4ab99284d1a053061235f8c2fa02a5da/src/gui/plugins/component_inspector/ComponentInspector.cc#L1116)

**Comment by iche033** [comment]
actually I think it still blocks. I see this [workaround](https://github.com/gazebosim/gz-sim/blob/f6efeefb4ab99284d1a053061235f8c2fa02a5da/test/integration/scene_broadcaster_system.cc#L475-L481) in the test.

**Comment by shameekganguly** [comment]
Thanks for the pointer Ian, I can use the thread workaround. Am still wondering if this is working as intended. If so, please feel free to close this bug.

**Comment by iche033** [comment]
I recall that the `/world/<world_name>/state_async` topic was created due to this issue. Our GUI has also switched to using the async topic as well. It's not very well documented. I'll close this issue since an alternative topic / workaround exists.
