### ISSUE TITLE
The geometry element of collision [collision] couldn't be created

### ISSUE THREAD

**Issue by frede791** [gazebosim/gz-sim#2262]
## Environment
* OS Version: 22.04
* Source  main branch most recent gz garden release

When running several worlds from fuel gazebo, the `[Err] [SDFFeatures.cc:843] The geometry element of collision [collision] couldn't be created` still appears. It was reported closed [here](https://github.com/gazebosim/gz-sim/issues/1828) but a user recently noted that it still appears for them as well. 

## Description
* Expected behavior: When starting some world using `gz sim -r /path/to/world.sdf` I would expect just the world to load and no error to appear. 
* Actual behavior: The world loads but the above mentioned error `[Err] [SDFFeatures.cc:843] The geometry element of collision [collision] couldn't be created` appears. This is not supposed to happen. 

## Steps to reproduce

1. Download the sdf file from https://app.gazebosim.org/OpenRobotics/fuel/worlds/Null%20Island
2. Start it with `gz sim -r /path/to/null/island.sdf`

## Output
![image](https://github.com/gazebosim/gz-sim/assets/80588263/ef9dcbe3-d948-462f-82dd-d3bd2cd066ed)

**Comment by azeey** [comment]
The error was reduced to a debug message in Harmonic in https://github.com/gazebosim/gz-physics/pull/531. We need to backport it to Garden.

**Comment by iche033** [comment]
backport in https://github.com/gazebosim/gz-physics/pull/581
