### ISSUE TITLE
oritentation of child sensor using set_pose service

### ISSUE THREAD

**Issue by jpvr20** [gazebosim/gz-sim#2278]
Hello,

I'm trying to change the orientation of sensor present inside (model->base_link->rgbd_camera) using the /world/<world_name>/set_pose service. When I change the orientation of parent model, it works fine but I when I try to do the same in the child sensor, it doesn't work. Is it possible to do using this or any other service? or using c++?

**Comment by azeey** [comment]
Only the poses of models can be changed with the `set_pose` service. To dynamically change the pose of a sensor, I think you'll have to attach it's parent link to a joint and command the position of the joint.
