### ISSUE TITLE
🧑‍🌾  `UNIT_Server_Test` `ServerConfigRealPlugin` flaky stuck in gazebo6 focal

### ISSUE THREAD

**Issue by Crola1702** [gazebosim/gz-sim#2282]
Reference build: https://build.osrfoundation.org/job/gz_sim-ci-ign-gazebo6-focal-amd64/14/consoleFull

Test regression: [UNIT_Server_TEST.test_ran](https://build.osrfoundation.org/job/gz_sim-ci-ign-gazebo6-focal-amd64/14/testReport/junit/(root)/UNIT_Server_TEST/test_ran/)

Specifially, the test failing is `ServerConfigRealPlugin`. Its average run time test is 1.8 seconds (1800 ms)

When it fails the following output is shown:

```
35: [Msg] Resource path add service on [/gazebo/resource_paths/add].
35: [Msg] Resource path get service on [/gazebo/resource_paths/get].
 35/273 Test  #35: UNIT_Server_TEST ........................................***Timeout 240.10 sec
```

This means the test is sometimes stuck when the `Resource path get service` is shown.

**Comment by azeey** [comment]
I believe this has been fixed as part of https://github.com/gazebosim/gz-sim/pull/2275. It hasn't failed in the 5 builds since https://build.osrfoundation.org/job/gz_sim-ci-ign-gazebo6-focal-amd64/14/
