### ISSUE TITLE
Thread safety in custom rendering sensor system (DopplerVelocityLogSystem.cc)

### ISSUE THREAD

**Issue by 5p00kk** [gazebosim/gz-sim#2289]
## Description
In DopplerVelocityLogSystem.cc there are time-related variables: nextUpdateTime, simTime. They appear to be used by both: the rendering thread (OnRedner, PostRender) and physics thread (DoPostUpdate). There seems to be no thread safety for these variables, compared to for instance pendingRequests which is atomic.

**Comment by azeey** [comment]
Thanks for catching those. There does seem to be a race condition on those variables. Would you be able to submit a PR?

**Comment by sauk2** [comment]
@azeey Could I work on this?

**Comment by azeey** [comment]
Yes, please go ahead. I'll assign it to you.

**Comment by sauk2** [comment]
> Yes, please go ahead. I'll assign it to you.

Would like to know your opinion on a possible implementation idea here:

- Have a single mutex to protect both `simTime` and `nextUpdateTime`.
- Lock the mutex at the start of the [`OnRender`](https://github.com/gazebosim/gz-sim/blob/5944188294511a60b829f88851edeaded0b72a84/src/systems/dvl/DopplerVelocityLogSystem.cc#L583-L632) and [`OnPostRender`](https://github.com/gazebosim/gz-sim/blob/5944188294511a60b829f88851edeaded0b72a84/src/systems/dvl/DopplerVelocityLogSystem.cc#L635-L646) functions.
- [This](https://github.com/gazebosim/gz-sim/blob/5944188294511a60b829f88851edeaded0b72a84/src/systems/dvl/DopplerVelocityLogSystem.cc#L354-L405) `if` block in `DoPostUpdate` uses both variables. Break it down into a nested `if` and lock the mutex inside it.
