### ISSUE TITLE
INTEGRATION_thruster has undefined behavior potentially causing test flakiness

### ISSUE THREAD

**Issue by azeey** [gazebosim/gz-sim#2291]
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build? gz-sim7, 926923f6644ce1d2ef68316bb20432c88cd3b75e

## Description
* Expected behavior: Code has no undefined behaviors
* Actual behavior:  `std::vector::back` is potentially called on an empty vector in multiple places. This is regarded as [undefined behavior](https://en.cppreference.com/w/cpp/container/vector/back). For example:
https://github.com/gazebosim/gz-sim/blob/926923f6644ce1d2ef68316bb20432c88cd3b75e/test/integration/thruster.cc#L335-L340

The vector `modelPoses` is cleared followed by `auto latest_pose = modelPoses.back();`

**Comment by GauravKumar9920** [comment]
can I work on this issue ?

**Comment by azeey** [comment]
Yes, please!

**Comment by azeey** [comment]
Hi @GauravKumar9920, this issue is not about code style, but that accessing `std::vector::back` on an empty vector could cause a crash.
