### ISSUE TITLE
Add documentation to build Gazebo from source for Linux (all distros). 

### ISSUE THREAD

**Issue by nishanthdmello** [gazebosim/gz-sim#2327]
I use endevour os and i was not able to install gazebo in any way. I wasn't able to install it from AUR or directly from source(.tar.gz or .tar.bz2 files or from github). Please fix this issue by providing an eleborate documentation to install gazebo an arch linux.

**Comment by azeey** [comment]
I think it would be great if Gazebo was available in the AUR, but the core team has no plans to do that. It would have to be done by other members of the community. Regarding building from source, I think @mjcarroll's suggestion should be sufficient. I don't think we want to add specific instructions for Arch or any other distro for installing the necessary dependencies.
