### ISSUE TITLE
../src/intel/isl/isl.c:2105: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.

### ISSUE THREAD

**Issue by AnishMathewOommen** [gazebosim/gz-sim#2364]
Please help me to solve this issue

Using Ros : Noetic (20.04 version)
When I run gazebo I get the below error
gazebo
../src/intel/isl/isl.c:2105: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.

**Comment by azeey** [comment]
If you think this is a bug, please fill out the issue [template](https://github.com/gazebosim/gz-sim/blob/gz-sim8/.github/ISSUE_TEMPLATE/bug_report.md) provided when you opened the issue. If you think it might be an issue with your local setup, https://robotics.stackexchange.com/ would be a better place to ask.

**Comment by AnishMathewOommen** [comment]
Thank you for your help @azeey

**Comment by AnishMathewOommen** [comment]
**Found the Solution for the above problem**
Please type the below commands in the terminal the issue will be solved( Updating Mesa driver)

```
sudo add-apt-repository ppa:kisak/kisak-mesa
sudo apt update
sudo apt upgrade

```


Reference document: https://itsfoss.com/install-mesa-ubuntu/
