### ISSUE TITLE
:farmer: Integation NetworkHandshake and ServerBroadcasterTest failing consistently in gz-sim-main

### ISSUE THREAD

**Issue by Crola1702** [gazebosim/gz-sim#2371]
## Environment
* OS Version: Ubuntu Jammy
* Source build

## Description
* Expected behavior: Test should pass
* Actual behavior: Tests are failing

## Steps to reproduce
1. Run a build in [gz_sim-ci-main-jammy-amd64](https://build.osrfoundation.org/job/gz_sim-ci-main-jammy-amd64/)
2. See tests fail

## Output
Reference build: https://build.osrfoundation.org/job/gz_sim-ci-main-jammy-amd64/63/

Test regressions:
* [NetworkHandshake.Updates](https://build.osrfoundation.org/job/gz_sim-ci-main-jammy-amd64/63/testReport/junit/(root)/NetworkHandshake/Updates/)
* [ServerRepeat/SceneBroadcasterTest.StateStatic/0](https://build.osrfoundation.org/job/gz_sim-ci-main-jammy-amd64/63/testReport/junit/(root)/ServerRepeat_SceneBroadcasterTest/StateStatic_0/)

#### Integration NetworkHandshake output

```
/home/jenkins/workspace/gz_sim-ci-main-jammy-amd64/gz-sim/test/integration/network_handshake.cc:220
Expected: (100u) <= (zPos.size()), actual: 100 vs 70
```

#### Integration ServerRepeat output

```
/home/jenkins/workspace/gz_sim-ci-main-jammy-amd64/gz-sim/test/integration/scene_broadcaster_system.cc:588
Expected: (stepMsg.stats().real_time().nsec()) < (_msg.stats().real_time().nsec()), actual: 928317066 vs 29291622
```

None of the test has changed in the last 2 years:
* [SceneBroadcaster code](https://github.com/gazebosim/gz-sim/blob/77f4c00308402f816fb2d253318b5626aea7911a/test/integration/scene_broadcaster_system.cc#L542)
* [Network handshake code](https://github.com/gazebosim/gz-sim/blob/77f4c00308402f816fb2d253318b5626aea7911a/test/integration/network_handshake.cc#L131)

**Comment by azeey** [comment]
This should be fixed now.

**Comment by azeey** [comment]
Closing since https://build.osrfoundation.org/job/gz_sim-ci-main-jammy-amd64/68/ is green
