### ISSUE TITLE
Docs: Add tutorial on how to start/pause simulator from CLI

### ISSUE THREAD

**Issue by Ryanf55** [gazebosim/gz-sim#2380]
## Desired behavior
Add  a new tutorial similar to [reset](https://github.com/gazebosim/gz-sim/blob/gz-sim8/tutorials/reset_simulation.md) that shows how to start/stop.  Context: https://discord.com/channels/1077825543698927656/1080763334384697430/1232059825634934875

## Alternatives considered
N/A

## Implementation suggestion

* Show start/pause button in GUI and what it does
* Explain how sim time stops and how to check sim time and iterations in CLI
* Explain how to start/pause with the `gz` CLI through transport
* Add a demo video

```bash
gz sim -s shapes.sdf
gz service -s /world/shapes/control --reqtype gz.msgs.WorldControl --reptype gz.msgs.Boolean --timeout 3000 --req 'pause: false'
gz topic -e -t /stats -n 1
sim_time {
  sec: 2
  nsec: 807000000
}
real_time {
  sec: 2
  nsec: 824597858
}
iterations: 2807
real_time_factor: 0.99667211181863757
step_size {
  nsec: 1000000
}
```

## Additional context

Please assign this to me. I'll write the tutorial.

**Comment by Ryanf55** [comment]
I would like to create a `gif` like the other tutorial. Can the maintainers recommend a process to do that? Or, is it OK to do the tutorial without a gif. Otherwise, I have the content ready.

**Comment by mjcarroll** [comment]
> I would like to create a gif like the other tutorial. Can the maintainers recommend a process to do that? Or, is it OK to do the tutorial without a gif. Otherwise, I have the content ready.

I don't know that we have a guide, but we have historically used https://en.wikipedia.org/wiki/Peek_(software) to record gifs on Linux.

**Comment by Ryanf55** [comment]
Thanks. Which world is shown in other tutorial?
