### ISSUE TITLE
Add image texture

### ISSUE THREAD

**Issue by rafal-gorecki** [gazebosim/gz-sim#2421]
Hello,
Is there any example or code to show how to somehow spawn entiti/marker with image texture in gazebo? For example spawn flat marker with specific image. It can be then used to implement https://github.com/gazebosim/gz-sensors/issues/427 this task.

**Comment by azeey** [comment]
Thanks for the issue, but this is a type of question that is best asked on https://robotics.stackexchange.com/. I encourage you to post your question there and if you find that there's a specific bug or feature request, come back and create a new issue here. In the mean time, I'll go ahead and close this.
