### ISSUE TITLE
Can't start new worlds

### ISSUE THREAD

**Issue by rfpg1** [gazebosim/gz-sim#2438]
## Environment
OS Version: Ubuntu 24.04
Binary install: Gazebo Harmonic LTS

## Details

Im new to gazebo and still trying to understand how it works

Just installed gazebo harmonic on a fresh install of Ubuntu 24.04, also have ros2 jazzy if it matter

However i can't do gz sim shapes.sdf

Get this error: 
```
The 'gz' command provides a command line interface to the Gazebo Tools.

 gz <command> [options]

List of available commands:

  help:          Print this help text.
  log:           Record or playback topics.
  msg:           Print information about messages.
  param:         List, get or set parameters.
  service:       Print information about services.
  topic:         Print information about topics.

Options:

  --force-version <VERSION>  Use a specific library version.
  --versions                 Show the available versions.
  --commands                 Show the available commands.
Use 'gz help <command>' to print help for a command.
```

## Description

Expected behavior: Shouldn't a world open?
Actual behavior: Nothing happens

## Steps to reproduce

1. Install Gazebo Harmonic TLS from source
2. Try to do gz sim

## Help

If you need more information let me know

Thanks for your help

**Comment by rfpg1** [comment]
Updates
Found the actual problem, I have ros2 jammy when i installed: sudo apt install ros-jazzy-ros-gz-bridge lost access to gz sim and some others
## Previous output of gz:
```
The 'gz' command provides a command line interface to the Gazebo Tools.

  gz <command> [options]

List of available commands:

  help:          Print this help text.
  fuel:          Manage simulation resources.
  gui:           Launch graphical interfaces.
  launch:        Run and manage executables and plugins.
  log:           Record or playback topics.
  model:         Print information about models.
  msg:           Print information about messages.
  param:         List, get or set parameters.
  plugin:        Print information about plugins.
  sdf:           Utilities for SDF files.
  service:       Print information about services.
  sim:           Run and manage the Gazebo Simulator.
  topic:         Print information about topics.

Options:

  --force-version <VERSION>  Use a specific library version.
  --versions                 Show the available versions.
  --commands                 Show the available commands.
Use 'gz help <command>' to print help for a command.
```

## Current output of gz:

```
The 'gz' command provides a command line interface to the Gazebo Tools.

  gz <command> [options]

List of available commands:

  help:          Print this help text.
  log:           Record or playback topics.
  msg:           Print information about messages.
  param:         List, get or set parameters.
  service:       Print information about services.
  topic:         Print information about topics.

Options:

  --force-version <VERSION>  Use a specific library version.
  --versions                 Show the available versions.
  --commands                 Show the available commands.
Use 'gz help <command>' to print help for a command.
```

Any ideas?

**Comment by rfpg1** [comment]
Tried to uninstall but didn't solve and i need that bridge so wouldn't be a solution anyway

**Comment by rfpg1** [comment]
Managed to fix this

All I had to do was: ros-jazzy-gz-sim-vendor as mencioned here: https://community.gazebosim.org/t/gazebo-harmonic-packages-available-on-ubuntu-noble/2772/8

**Comment by isaac-hash** [comment]
[gz-1] Invalid arguments
[ERROR] [gz-1]: process has died [pid 298835, exit code 255, cmd 'gz sim -r /home/genesys/robo/install/my_demo_gazebo/share/my_demo_gazebo/worlds/empty.world'].

Can anyone help with this
I've been hitting this issue all day

world_file = LaunchConfiguration('world')
    headless = LaunchConfiguration('headless')

    declare_world = DeclareLaunchArgument(
        'world',
        default_value='empty.world',
        description='World file name (inside package worlds/ folder)'
    )

    declare_headless = DeclareLaunchArgument(
        'headless',
        default_value='false',
        description='true → no GUI'
    )

    # --- NEW: Define the absolute path using PathJoinSubstitution ---
    # This ensures the full, unambiguous path is passed to 'gz sim'
    absolute_world_path = PathJoinSubstitution([
        os.path.join(pkg_share, 'worlds'),
        world_file
    ])

    # ────── Set Gazebo resource path so gz can find your world ──────
    set_gz_resource_path = SetEnvironmentVariable(
        name='GAZEBO_RESOURCE_PATH',
        value=os.path.join(pkg_share, 'worlds')
    )

    # ────── Gazebo execute processes ──────
    gz_sim_headless = ExecuteProcess(
        # Use the absolute path substitution here as the positional argument
        cmd=['gz', 'sim', '-r', '--headless', absolute_world_path],
        output='screen',
        additional_env={'IGN_GAZEBO_SYSTEM_PLUGIN_PATH': '/opt/ros/humble/lib'},
        condition=IfCondition(headless)
    )

    gz_sim_gui = ExecuteProcess(
        # Use the absolute path substitution here as the positional argument
        cmd=['gz', 'sim', '-r', absolute_world_path],
        output='screen',
        additional_env={'IGN_GAZEBO_SYSTEM_PLUGIN_PATH': '/opt/ros/humble/lib'},
        condition=UnlessCondition(headless)
    )
