### ISSUE TITLE
Tracked Vehicle example issue

### ISSUE THREAD

**Issue by huzzu7** [gazebosim/gz-sim#2495]
## Environment
* OS Version: 

## Description
I am on the ign-gazebo6 branch and am trying to run the tracked_vehicle_simple.sdf example with the command `ign gazebo tracked_vehicle_simple.sdf` . I am able to publish to the /keyboard/keypress topic. Running the subsequent command `ign topic -t /keyboard/keypress -e` and pressing the W key, the output is `data: 87` .  However the robot doesn't move in simulation. I am wondering if the example has the correct plugins.

**Comment by azeey** [comment]
If you're using Fortress and Garden, the tracked vehicle example requires building Gazebo from source with a DART 6.13 or later. See https://github.com/gazebosim/gz-sim/issues/1662

It would be good to mention this in the examples.

**Comment by huzzu7** [comment]
I see, thank you. I switched to Harmonic and the example works fine.
