### ISSUE TITLE
Force torque sensor plugin not detecting wrench

### ISSUE THREAD

**Issue by fafux** [gazebosim/gz-sim#2544]
## Environment
* OS Version: Ubuntu 24.04
* Source or binary build?
  Binary Gazebo Harmonic 8.5.0

## Description
* Behavior: I include a force torque system plugin in a xacro file  in the following way: 
```bash
<gazebo reference="${prefix}fts_link_joint">
    <sensor type="force_torque" name="force_torque">
        <update_rate>30.0</update_rate>
        <always_on>true</always_on>
        <visualize>true</visualize>
        <topic>ft_sensor/wrench</topic>
        <force_torque name="ati_axia">
        </force_torque>
        <plugin
          filename="gz-sim-forcetorque-system"
          name="gz::sim::systems::ForceTorque">
        </plugin>
    </sensor>
</gazebo>
```
I run the simulation, in which the link of the sensor (associated with a mesh, both visual and collision) is attached to a robot through a joint. If the sensor has a physical contact with an object directly, the measured wrench has a reasonable value. If I add a link of an end-effector (associated with a mesh, both visual and collision), attached to the sensor with a fixed joint, and this end-effector has the contact with the object, and the ft sensor is not in contact with the object directly, the ft sensor does not measure any wrench. 
How should I solve it?

**Comment by azeey** [comment]
Thanks for the issue, but this is a type of question that is best asked on https://robotics.stackexchange.com/. I encourage you to post your question there and if you find that there's a specific bug or feature request, come back and create a new issue here. In the mean time, I'll go ahead and close this.
