### ISSUE TITLE
Typo in gz sim python api

### ISSUE THREAD

**Issue by CreeperLin** [gazebosim/gz-sim#2568]
The Python bindings define Joint.set_position_imits where it should be set_position_limits

https://github.com/gazebosim/gz-sim/blob/f600a441951c6ec0818008283b051a7770da1cd6/python/src/gz/sim/Joint.cc#L97

**Comment by ahcorde** [comment]
Fixed PR https://github.com/gazebosim/gz-sim/pull/2578
