### ISSUE TITLE
Ignition Gazebo Plugins

### ISSUE THREAD

**Issue by aarushjain355** [gazebosim/gz-sim#2636]
Does anyone know how to add an ignition gazebo plugin to a link or a joint defined in the sdf file. I am trying to rotate a certain link in my sdf file so I attached the libignition-gazebo-pose-publisher-system.so however for some reason i am unable to see the topic in ign topic -l.

**Comment by azeey** [comment]
Thanks for the issue, but this is a type of question that is best asked on https://robotics.stackexchange.com/. I encourage you to post your question there and if you find that there's a specific bug or feature request, come back and create a new issue here. In the mean time, I'll go ahead and close this.
