### ISSUE TITLE
Bug: Unable to Get Model Pose Info When publish_model_pose Is Set to True in Gazebo Harmonic

### ISSUE THREAD

**Issue by Kametor** [gazebosim/gz-sim#2690]
## Environment
* OS Version: Ubuntu 22.04
* Source or binary build: Binary build (Gazebo Harmonic)
  
  

## Description
* Expected behavior:
I am trying to get the model position info with respect to the Gazebo world frame. Based on my understanding, the pose publisher system should be used for this purpose. However, when I call the system with the publish_model_pose parameter set to true, I am unable to get the pose information. I checked it using the command:
gz topic -e -t "topic name"
After examining the source code of the system, I noticed that the publish_model_pose parameter is not being used. Instead, the publish_nested_model parameter is being checked, and it is set to false by default. When I changed the publish_nested_model parameter to true, I was successfully able to get the model pose information.
It seems that the nested_model_pose is used when there is no model_pose parameter. However, there doesn't appear to be a conditional check for this in the code. I believe this condition may be missing and could be causing the issue.

* Actual behavior: 
The model pose is not publishing unless you set True for publish_nested_model_pose
## Steps to reproduce

1. Use pose publisher system in a basic gazebo world.
2. Set the publish_model_pose parameter to true.
3. Try to get the model pose information via the appropriate topic.
4. Observe that no pose information is received.
5. Change the publish_nested_model parameter to true to successfully retrieve the model pose info.

## Output
Using pose publisher system with correct parameters
![Screenshot from 2024-12-02 16-32-39](https://github.com/user-attachments/assets/3ef754fe-c0b4-4ced-801a-ab50c5312859)

The missing if condition part in code
![Screenshot from 2024-12-02 16-28-05](https://github.com/user-attachments/assets/ce6c419c-37c1-4237-b67f-838cc1a25902)

**Comment by iche033** [comment]
fixed in https://github.com/gazebosim/gz-sim/pull/2697, will backport to harmonic once merged.

**Comment by TheNoobInventor** [comment]
Hello @iche033, I don't mean to reopen a closed issue but this bug fix hasn't been ported to Harmonic. 

I did make the same code changes you made in my fork of `gz-sim8` and it worked. Should I create a pull request for this or let you handle the backport? Thank you.

**Comment by iche033** [comment]
> Hello [@iche033[<img alt="" width="15" height="15" src="chrome-extension://dlebflppeeemcdpidccbiblndppbmjmh/ospo-chrome-ext-logo.png">](https://teams.googleplex.com/iche@google.com)](https://github.com/iche033), I don't mean to reopen a closed issue but this bug fix hasn't been ported to Harmonic.
> 
> I did make the same code changes you made in my fork of `gz-sim8` and it worked. Should I create a pull request for this or let you handle the backport? Thank you.

cool, just backported to gz-sim8 in https://github.com/gazebosim/gz-sim/pull/2946

**Comment by TheNoobInventor** [comment]
Thank you!
