### ISSUE TITLE
Configure user camera parameters from SDF

### ISSUE THREAD

**Issue by chapulina** [gazebosim/gz-sim#421]
It would be useful to make user camera parameters such as clip distances and FOV configurable from SDF, from within the `<plugin filename="GzScene3D...` tag. At the moment, it's possible to change those programmatically from any GUI plugin, but that isn't very convenient.

---

The motivation for this is that noticed that the default field of view of the user camera is different on Ignition and Classic, which means that the same camera poses on both simulators will have different views of the world.

It is 90 degrees on Ignition:

https://github.com/ignitionrobotics/ign-gazebo/blob/80cbc2ee0885cfa4ecebbca301916f5f74b8a4ca/src/gui/plugins/scene3d/Scene3D.cc#L1432

While on Classic it is 60 degrees:

https://github.com/osrf/gazebo/blob/10863ffa8ec28e8e0e3d3a3a588d21cdc78055ab/gazebo/rendering/UserCamera.cc#L141

**Comment by azeey** [comment]
This looks like it's already implemented.
