### ISSUE TITLE
👩‍🌾 INTEGRATION_physics_system flaky on macOS for Citadel

### ISSUE THREAD

**Issue by chapulina** [gazebosim/gz-sim#444]
The test has been passing consistently on Blueprint and Dome:

* https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo2-homebrew-amd64/159/testReport/(root)/PhysicsSystemFixture/history/
* https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo4-homebrew-amd64/5/testReport/(root)/PhysicsSystemFixture/history/

But it's flaky on Citadel:

* https://build.osrfoundation.org/job/ignition_gazebo-ci-ign-gazebo3-homebrew-amd64/74/testReport/junit/(root)/INTEGRATION_physics_system/test_ran/history/

Each time it failed at a different test case, but always with a segfault:

```
99: [ RUN      ] PhysicsSystemFixture.ResetPositionComponent
 99/144 Test  #99: INTEGRATION_physics_system ...........................***Exception: SegFault  5.39 sec
```

```
99: [ RUN      ] PhysicsSystemFixture.GetBoundingBox
 99/144 Test  #99: INTEGRATION_physics_system ...........................***Exception: SegFault  6.90 sec
```

**Comment by azeey** [comment]
Fixed by #1836.
