### ISSUE TITLE
Resource Spawner plugin showing owner's name twice

### ISSUE THREAD

**Issue by jennuine** [gazebosim/gz-sim#865]
## Environment
* OS Version: Ubuntu 20.04 Focal
* Source or binary build?
    both

## Description
* Expected behavior: Under "Fuel resources" expected to see owner's name appear in list once.
* Actual behavior: Owner's name appears twice but when one name is clicked it highlights both (the same owner name).

This was tested in both source and binary builds and does not happen on Ubuntu Bionic.

## Steps to reproduce

1. `ign gazebo`
2. Add "Resource Spawner" from plugin menu
3. Wait for fuel resources to be finished loading

## Output

![image](https://user-images.githubusercontent.com/8602001/122484744-1cc45f00-cf8a-11eb-842f-bcbb633b1fd0.png)

**Comment by azeey** [comment]
Fixed by #1962
